# -*- coding: utf-8 -*-
"""proyecto final

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1sN9jgWzCokZgb1oGyUupN7UH_0X47hxz
"""

estudiantes = []

# =========================
# AGREGAR ESTUDIANTE
# =========================
def agregar_estudiante():
    while True:
        id_est = input("Ingrese ID del estudiante: ").strip()
        if id_est.isdigit():
            break
        print("❌ numero de ID incorrecto intente de nuevo:")

    # Validar que no exista
    if any(e["id"] == id_est for e in estudiantes):
        print("❌ Ya existe un estudiante con ese ID\n")
        return

    nombre = input("Ingrese nombre del estudiante: ").strip()

    estudiantes.append({
        "id": id_est,
        "nombre": nombre,
        "notas": []
    })

    print("✅ Estudiante agregado correctamente\n")


# =========================
# LISTAR ESTUDIANTES
# =========================
def listar_estudiantes():
    if not estudiantes:
        print("⚠️ No hay estudiantes registrados\n")
        return

    print("\n📋 LISTA DE ESTUDIANTES")
    for est in estudiantes:
        print(f"ID: {est['id']} | Nombre: {est['nombre']} | Notas: {est['notas']}")
    print()


# =========================
# BUSCAR ESTUDIANTE
# =========================
def buscar_estudiante():
    opcion = input("Buscar por (1) ID o (2) Nombre: ")

    if opcion == "1":
        valor = input("Ingrese ID: ")
        encontrado = next((e for e in estudiantes if e["id"] == valor), None)
    elif opcion == "2":
        valor = input("Ingrese nombre: ").lower()
        encontrado = next((e for e in estudiantes if e["nombre"].lower() == valor), None)
    else:
        print("❌ Opción inválida\n")
        return

    if encontrado:
        print(f"✅ Encontrado: {encontrado}\n")
    else:
        print("❌ Estudiante no encontrado\n")


# =========================
# ELIMINAR (USANDO enumerate + pop)
# =========================
def eliminar_estudiante():
    id_est = input("Ingrese ID del estudiante a eliminar: ")

    for i, est in enumerate(estudiantes):
        if est["id"] == id_est:
            estudiantes.pop(i)
            print("🗑️ Estudiante eliminado correctamente\n")
            return

    print("❌ Estudiante no encontrado\n")


# =========================
# ACTUALIZAR ESTUDIANTE
# =========================
def actualizar_estudiante():
    id_est = input("Ingrese ID del estudiante: ")

    for est in estudiantes:
        if est["id"] == id_est:
            print("\n1. Cambiar nombre")
            print("2. Cambiar ID")
            print("3. Reemplazar notas")

            opcion = input("Seleccione opción: ")

            if opcion == "1":
                est["nombre"] = input("Nuevo nombre: ")

            elif opcion == "2":
                nuevo_id = input("Nuevo ID: ")
                if any(e["id"] == nuevo_id for e in estudiantes):
                    print("❌ Ese ID ya existe\n")
                    return
                est["id"] = nuevo_id

            elif opcion == "3":
                nuevas_notas = []
                print("Puede ingresar hasta 5 notas.")
                while len(nuevas_notas) < 5:
                    try:
                        nota = float(input(f"Ingrese nota {len(nuevas_notas) + 1} (o -1 para terminar): "))
                        if nota == -1:
                            break
                        if 0 <= nota <= 5:
                            nuevas_notas.append(nota)
                        else:
                            print("❌ Nota inválida (0 a 5)")
                    except:
                        print("❌ Entrada inválida")

                est["notas"] = nuevas_notas

            else:
                print("❌ Opción inválida\n")
                return

            print("✅ Estudiante actualizado\n")
            return

    print("❌ Estudiante no encontrado\n")


# =========================
# AGREGAR NOTAS
# =========================
def agregar_notas():
    id_est = input("Ingrese ID del estudiante: ")

    for est in estudiantes:
        if est["id"] == id_est:
            while True:
                if len(est["notas"]) >= 5:

                    break

                try:
                    nota = float(input(f"Ingrese nota ({len(est["notas"]) + 1}/5, o -1 para salir): "))

                    if nota == -1:
                        break

                    if 0 <= nota <= 5:
                        est["notas"].append(nota)
                    else:
                        print("❌ Nota debe estar entre 0 y 5")

                except:
                    print("❌ Entrada inválida")

            print("✅ Notas agregadas correctamente\n")
            return

    print("❌ Estudiante no encontrado\n")


# =========================
# PROMEDIO POR ESTUDIANTE
# =========================
def promedio_estudiante():
    id_est = input("Ingrese ID del estudiante: ")

    for est in estudiantes:
        if est["id"] == id_est:
            if est["notas"]:
                promedio = sum(est["notas"]) / len(est["notas"])
                print(f"📊 Promedio de {est['nombre']}: {promedio:.2f}\n")
            else:
                print("⚠️ No tiene notas\n")
            return

    print("❌ Estudiante no encontrado\n")


# =========================
# PROMEDIO GENERAL
# =========================
def promedio_general():
    todas = []

    for est in estudiantes:
        todas.extend(est["notas"])

    if todas:
        promedio = sum(todas) / len(todas)
        print(f"🌍 Promedio general: {promedio:.2f}\n")
    else:
        print("⚠️ No hay notas registradas\n")


# =========================
# MENÚ PRINCIPAL
# =========================
def menu():
    while True:
        print("===== SISTEMA DE GESTIÓN DE ESTUDIANTES =====")
        print("1. Agregar estudiante")
        print("2. Listar estudiantes")
        print("3. Buscar estudiante")
        print("4. Eliminar estudiante")
        print("5. Actualizar estudiante")
        print("6. Agregar notas")
        print("7. Promedio de un estudiante")
        print("8. Promedio general")
        print("9. Salir")

        opcion = input("Seleccione una opción: ")

        if opcion == "1":
            agregar_estudiante()
        elif opcion == "2":
            listar_estudiantes()
        elif opcion == "3":
            buscar_estudiante()
        elif opcion == "4":
            eliminar_estudiante()
        elif opcion == "5":
            actualizar_estudiante()
        elif opcion == "6":
            agregar_notas()
        elif opcion == "7":
            promedio_estudiante()
        elif opcion == "8":
            promedio_general()
        elif opcion == "9":
            print("👋 Saliendo del sistema...")
            break
        else:
            print("❌ Opción inválida\n")


# =========================
# EJECUCIÓN
# =========================
menu()